---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность купить товар из корзины. Нужна форма с именем, телефоном и адресом доставки
  - Внешний вид товаров на сайте должен быть привлекательным. Недопускаются фотографии низкого качества и не соответствующие описанию
  - Товары на сайте не должны нарушать требования законодательства РФ
  - Товары на сайте имеют оценку. Логично дать пользователю возможность влиять на неё. Нужна функция оценивания
